"""
Domain models and data structures for the Factory Simulation Core.
"""

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, List, Optional
import uuid
from datetime import datetime, timezone


class OperatingState(str, Enum):
    OFF = "OFF"
    STARTING = "STARTING"
    IDLE = "IDLE"
    RUNNING = "RUNNING"
    WARNING = "WARNING"
    FAULT = "FAULT"
    MAINTENANCE = "MAINTENANCE"
    RECOVERY = "RECOVERY"


class HealthState(str, Enum):
    HEALTHY = "HEALTHY"
    WARNING = "WARNING"
    FAULT = "FAULT"


class MachineType(str, Enum):
    CNC_MACHINING_CENTER = "CNC_MACHINING_CENTER"
    CNC_LATHE = "CNC_LATHE"
    INDUSTRIAL_ROBOT_6AXIS = "INDUSTRIAL_ROBOT_6AXIS"
    WELDING_ROBOT = "WELDING_ROBOT"
    INDUSTRIAL_CONVEYOR = "INDUSTRIAL_CONVEYOR"
    INDUSTRIAL_PRESS = "INDUSTRIAL_PRESS"
    INJECTION_MOLDING_MACHINE = "INJECTION_MOLDING_MACHINE"
    AIR_COMPRESSOR = "AIR_COMPRESSOR"
    INDUSTRIAL_PUMP = "INDUSTRIAL_PUMP"
    VISION_INSPECTION_STATION = "VISION_INSPECTION_STATION"
    AUTONOMOUS_MOBILE_ROBOT = "AUTONOMOUS_MOBILE_ROBOT"
    INDUSTRIAL_CHILLER = "INDUSTRIAL_CHILLER"


class ProtocolMetadata(str, Enum):
    OPC_UA = "OPC_UA"
    MODBUS_TCP = "MODBUS_TCP"
    MQTT = "MQTT"


class SignalType(str, Enum):
    FLOAT = "FLOAT"
    INT = "INT"
    BOOL = "BOOL"
    STRING = "STRING"
    ENUM = "ENUM"


class InvalidStateTransitionError(Exception):
    """Raised when an invalid machine operating state transition is attempted."""
    pass


@dataclass
class SignalDefinition:
    name: str
    unit: str
    signal_type: SignalType
    min_value: Optional[float] = None
    max_value: Optional[float] = None
    nominal_value: Any = None
    description: str = ""

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SignalDefinition":
        return cls(
            name=data["name"],
            unit=data.get("unit", ""),
            signal_type=SignalType(data.get("type", "FLOAT")),
            min_value=data.get("min"),
            max_value=data.get("max"),
            nominal_value=data.get("nominal"),
            description=data.get("description", "")
        )


@dataclass
class MachineProfile:
    machine_id: str
    machine_type: MachineType
    protocol_metadata: ProtocolMetadata
    plant_id: str = "PLANT_01"
    line_id: str = "LINE_A"
    description: str = ""
    nominal_load: float = 70.0
    signals: List[SignalDefinition] = field(default_factory=list)

    @classmethod
    def from_dict(cls, data: Dict[str, Any], plant_id: str = "PLANT_01", line_id: str = "LINE_A") -> "MachineProfile":
        signals = [SignalDefinition.from_dict(s) for s in data.get("signals", [])]
        return cls(
            machine_id=data["machine_id"],
            machine_type=MachineType(data["machine_type"]),
            protocol_metadata=ProtocolMetadata(data["protocol_metadata"]),
            plant_id=plant_id,
            line_id=line_id,
            description=data.get("description", ""),
            nominal_load=float(data.get("nominal_load", 70.0)),
            signals=signals
        )


@dataclass
class SimulationGroundTruth:
    """
    Simulator-internal ground truth data used solely for simulation, scenario tracking,
    and supervisory testing.

    IMPORTANT: Ground truth data MUST NEVER be merged into public telemetry measurement payloads.
    """
    degradation_level: float = 0.0  # 0.0 (new) to 100.0 (failure)
    scenario_id: str = "NORMAL_OPERATION"
    fault_label: Optional[str] = None
    active_conditions: Dict[str, float] = field(default_factory=dict)
    hidden_wear_counter: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "degradation_level": round(self.degradation_level, 4),
            "scenario_id": self.scenario_id,
            "fault_label": self.fault_label,
            "active_conditions": dict(self.active_conditions),
            "hidden_wear_counter": round(self.hidden_wear_counter, 4)
        }


@dataclass
class TelemetrySnapshot:
    """
    Snapshot of telemetry generated by a machine at a specific simulation timestep.
    Contains strictly public measurements for normal consumption and isolated ground-truth.
    """
    schema_version: str
    event_id: str
    machine_id: str
    machine_type: str
    protocol_metadata: str
    timestamp: str
    sequence: int
    operating_state: str
    health_state: str
    public_measurements: Dict[str, Any]
    ground_truth: SimulationGroundTruth

    def to_dict(self, include_ground_truth: bool = False) -> Dict[str, Any]:
        """
        Convert snapshot to dictionary representation.
        By default, ground_truth is excluded from the returned payload to prevent target leakage.
        """
        result = {
            "schemaVersion": self.schema_version,
            "eventId": self.event_id,
            "machineId": self.machine_id,
            "machineType": self.machine_type,
            "protocolMetadata": self.protocol_metadata,
            "timestamp": self.timestamp,
            "sequence": self.sequence,
            "state": {
                "operating": self.operating_state,
                "health": self.health_state
            },
            "measurements": self.public_measurements
        }
        if include_ground_truth:
            result["_simulationGroundTruth"] = self.ground_truth.to_dict()
        return result
